### ISSUE TITLE
建议增加封面上传，及反馈杀毒软件误报现象

### ISSUE THREAD

**Issue by oscarwty** [ForgQi/Caution#13]
现在一次性传封面还要用cli版，希望gui也能增加这个功能，谢谢~
另外现在windows只有msi可用，但是卡巴斯基会报毒（应该是误报）
事件: 进程已终止
应用程序: Windows® installer
用户: MELTDOWN\Administrator
用户类型: 活动用户
组件: 系统监控
结果说明: 已终止
类型: 木马
名称: PDM:Trojan.Win32.Generic
威胁级别: 高
对象类型: 进程
对象路径: C:\Windows\System32
对象名称: msiexec.exe

**Comment by ForgQi** [comment]
封面后面会加上，报毒这个事情不知道怎么处理，有啥方法可以解决吗

**Comment by oscarwty** [comment]
> 封面后面会加上，报毒这个事情不知道怎么处理，有啥方法可以解决吗

盲猜一个不调用installer的绿色免安装发布可能就好了？

**Comment by ForgQi** [comment]
试一下新版，可以上传封面了

**Comment by oscarwty** [comment]
> 试一下新版，可以上传封面了

谢谢，能用了，另外我暂时添加了杀毒软件排除项
如果能做成绿色版可能就完全不报毒了

**Comment by oscarwty** [comment]
> 试一下新版，可以上传封面了

他突然不报毒了，应该没事了
