### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by ilharp** [ForgQi/Caution#5]
启动 GUI 或执行任何操作均报错

```
OSError: [Errno 2] No such file or directory
```

**Comment by ForgQi** [comment]
这个应该是不影响登录的，有截图或者更多信息吗

**Comment by ilharp** [comment]
无法登录，且除了右上角弹出这个提示以外没有任何更多信息。

目前已经通过 biliup 和 biliup-rs 结合完成了多 P 投稿，问题倒算是解决了

不过这个问题还是很诡异  之前只在使用某些不支持路径中含空格的 Python 程序中遇到过

**Comment by ForgQi** [comment]
用的是扫码登录吗

**Comment by ilharp** [comment]
是的

**Comment by ilharp** [comment]
刚才又安装看了下，直接把 biliup-rs 生成的 `cookies.json` 扔进程序目录里倒是可以直接跳过登录步骤了

**Comment by ilharp** [comment]
不过点击任何按钮依旧会报

```
OSError: [Errno 5] Input/output error
```

![image](https://user-images.githubusercontent.com/20179549/151667122-befe3730-3a88-497b-b799-2726bbcd7ff1.png)

**Comment by ForgQi** [comment]
是Linux吗

**Comment by ilharp** [comment]
是 Windows

**Comment by ilharp** [comment]
又双叕看了下，以管理员启动就可以解决问题了

以下是小声逼逼：所以这就是 Windows 一个很优秀也是很傻逼的权限管理问题，程序操作 `Program Files` 是需要提权的

因此个人比较建议任何现代应用都应该安装在 `%USERPROFILE%\AppData\Local\Programs` 下（甚至更为激进地强制安装到此目录，以避免提权问题

**Comment by ilharp** [comment]
已测试确认管理员启动可以同时解决扫码登录的问题 单纯是没有权限保存 `cookies.json`

**Comment by ForgQi** [comment]
安装这一块确实不太了解，我可能应该把配置文件移到用户目录，还是怎么处理好一些。因为考虑免安装的情况下，是不是直接保存在当前目录数据文件好找一些

**Comment by ilharp** [comment]
安装这块确实是比较难处理的问题，尤其是对跨平台 GUI 来说

我个人现在也是能用便携版就用便携版（ 然后打开 [Releases](https://github.com/ForgQi/Caution/releases/tag/v0.0.4) 发现这里标着有 exe 但却没有文件下载

以下是个人之前处理用户数据相关问题的一点思路，前提条件都是所有用户数据（多个数据库文件或配置文件）都可以存放在单一目录下

## Windows

### Portable（推荐）

向用户提供 `.exe` 或 `.zip`，下载解压即用，此时的用户数据可存放在 `cwd` 下，也可创建子目录，无权限问题，无迭代问题

### Per-User Installer（推荐）

推荐提供，安装器默认安装到 `%USERPROFILE%\AppData\Local\Programs` 下，此时的用户数据也可存放在 `cwd` 下，也可创建子目录，无权限问题，无迭代问题

### System-Wide Installer（不推荐）

不推荐提供，安装器默认安装到 `%ProgramFiles(x86)%` 下，此时程序无 `cwd` 权限，程序需要自行在 `%APPDATA%`（即 `%USERPROFILE%\AppData\Roaming`）下创建用户数据文件夹并使用，无迭代问题

## macOS

（Mac 浅用户所以不太了解

### Portable（推荐）

向用户提供 Binary 或 `.zip`，下载解压即用，此时的用户数据可存放在 `cwd` 下，也可创建子目录，无权限问题，无迭代问题，但要注意可能存在需 `chmod +x` 问题

### App（用户数据 `cwd`）（不推荐）

提供 `app.tar.gz` 或 `.dmg`，可以安装入 `/Applications` 里使用 LaunchPad 打开，此时的用户数据可存放在 `cwd` 下，也可创建子目录，无权限问题，**有迭代问题，用户数据可能在应用版本更新后消失**

### App（推荐）

提供 `app.tar.gz` 或 `.dmg`，可以安装入 `/Applications` 里使用 LaunchPad 打开，程序需要自行在 `~/Library` 下创建用户数据文件夹并使用，无迭代问题

## Linux

你都用 Linux 了（省略 XvX

无论 AppImage 还是 deb 个人不推荐 `cwd`，deb 有权限问题 AppImage 有迭代问题，可以考虑 `/etc`

**Comment by ilharp** [comment]
我自己写的几个 GUI 项目，一般只会提供

- Windows Portable

- Windows Per-User

- macOS Portable

- macOS dmg

- Linux Portable

这五种，如果比较懒的话就可以不做差异处理了，直接暴力 `cwd` 下建数据文件夹，然后让 macOS 用户自行备份数据（XvX

**Comment by ForgQi** [comment]
好的感谢大佬了。还想问一下mac应用签名这一块，除了交钱然后签名之外，是没有别的方法能运行未签名的应用了吗

**Comment by ilharp** [comment]
www我不是大佬啦

Mac 的话我是浅度用户不太了解，至少在我的电脑上看 App 包不需要签名也可以运行的，首次启动 App 的时候系统会提示去设置里把受信任开发者打开，有个按钮点一下就行

![image](https://user-images.githubusercontent.com/20179549/151673669-ac6e4e9d-2f08-43d1-979a-6f0f9fc4e847.png)

我一般打 App 包都是直接把文件 `chmod +x` 以后放进去就完事了，然后会用 [create-dmg](https://github.com/sindresorhus/create-dmg) 打 dmg 包

如果想要在设置里仅 App Store 的状态下直接运行的话那应该就必须要给水果上供了

**Comment by ForgQi** [comment]
我是听说好像mac从catalina开始把这个选项去掉了，因为没有用过不太清楚，catalina以上的版本也是有这个选项的吗

**Comment by ForgQi** [comment]
我是听说好像mac从catalina开始把这个选项去掉了，因为没有用过不太清楚，catalina以上的版本也是有这个选项的吗

**Comment by ilharp** [comment]
被去掉的应该是任意来源，受信开发者来源应该还是可以在设置里点一下就正常运行的

但因为我是把系统保护什么的都关了我也不太清楚  不知道是不是有这方面的原因

这方面还是建议去问问别的资深水果人  或者等出了问题再解决（趴

**Comment by ForgQi** [comment]
灰常感谢，没有经验所以问题有点多😂
